// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BasicDrawer: typeof import('./src/components/common/BasicDrawer/BasicDrawer.vue')['default']
    BasicDrawerFooter: typeof import('./src/components/common/BasicDrawer/compontents/BasicDrawerFooter.vue')['default']
    BasicDrawerHeader: typeof import('./src/components/common/BasicDrawer/compontents/BasicDrawerHeader.vue')['default']
    BasicHelp: typeof import('./src/components/common/BasicHelp/BasicHelp.vue')['default']
    BasicTitle: typeof import('./src/components/common/BasicTitle/BasicTitle.vue')['default']
    ScrollContainer: typeof import('./src/components/common/ScrollContainer/ScrollContainer.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
  }
}

export { }
